### ISSUE TITLE
dont work with tornado 2.4post1

### ISSUE THREAD

**Issue by abdelouahabb** [marcelnicolay/mongotor#19]
here is what i got:
http://groups.google.com/group/mongodb-user/browse_thread/thread/a856f416a1459069
http://stackoverflow.com/questions/13267805/cant-get-connexion-using-mongotor

**Comment by marcelnicolay** [comment]
Tornado 2.4post1 no longer has the method 'running' in ioloop. I don't know why they remove this method, but this break the mongotor. mongotor works very well in tornado 2.3 and 2.4, you can use one of these while i work on fixing this

**Comment by abdelouahabb** [comment]
yes, now it works.
so like they you must add something that verify the version of tornado and decide which method to use :(

**Comment by abdelouahabb** [comment]
update: this works in tornado 2.4.1
seems that the post1 is the future tornado 3.0

**Comment by abdelouahabb** [comment]
congratulations, and welcome back ;)
