### ISSUE TITLE
$gt,..., $unwind, aggregate

### ISSUE THREAD

**Issue by abdelouahabb** [marcelnicolay/mongotor#21]
hi
now it is possible to use distinct, how about queries that uses dollar sign?
and what about aggregation?
it seems that i've a great stomac to hope this :dancers:

**Comment by marcelnicolay** [comment]
You can use all of mongo operators, just put inside quotes.... 

for example: 
db.users.find({'friends': {'$gt': '10'}}, callback=callback)
db.users.find({'friends': {'$in': [1, 2]}}, callback=callback)

**Comment by abdelouahabb** [comment]
and what about aggregate? it need the method aggregate()

**Comment by marcelnicolay** [comment]
aggregate() is merely a wrapper around the database command aggregate. you can use db.command() to run commands....

take a look here:
http://docs.mongodb.org/manual/reference/commands/#aggregate

**Comment by abdelouahabb** [comment]
hope this will be in the next update as the python zen says:
Explicit is better than implicit  :+1:

**Comment by marcelnicolay** [comment]
you are right... I implemented  wrapper for aggreate and group...

you can see aggregate in use here:
https://github.com/marcelnicolay/mongotor/commit/35e3d2a91328cdd1e96246d2a66f8c3e824cc0b0#L4R229

**Comment by abdelouahabb** [comment]
oh yeah ;)
thank you :)
now there is only GridFS because i got problem, it seems that the browser hangs because of gridfs?
http://stackoverflow.com/questions/13351405/how-do-i-use-gridfs-with-libraries-that-dont-accept-non-blocking-gridfs
