### ISSUE TITLE
cant catch IntegrityError

### ISSUE THREAD

**Issue by abdelouahabb** [marcelnicolay/mongotor#23]
hi, i cant catch IntegrityError:
i use email as an "_id" so i try to redirect to a page "passloss" for a user that tries to use an email that has already been used.
...

try:
    yield tornado.gen.Task(db.users.insert, user)
except mongotor.errors.IntegrityError:
    print "hoo"
    self.redirect("/passloss")

i get this:
No handlers could be found for logger "mongotor.connection"

because i can catch other errors:

try:
    ....
except (mongotor.errors.InterfaceError, mongotor.errors.DatabaseError):
    self.redirect("/error")

**Comment by marcelnicolay** [comment]
I was working in safe write operations, like insert and update, and I finished this today...

Try again, now integrity error will be raised

**Comment by abdelouahabb** [comment]
ok, thank you
i'll try it when i'll be at home :)
