### ISSUE TITLE
safe writes

### ISSUE THREAD

**Issue by abdelouahabb** [marcelnicolay/mongotor#25]
hi
pymongo now support safe writes dy default, how can this affect mongotor?
http://emptysquare.net/blog/pymongos-new-default-safe-writes/
EDIT: mongotor dont use pymongo, only bson module.

**Comment by marcelnicolay** [comment]
mongotor already is implemented with a client layer that performs safe writes by default.

**Comment by abdelouahabb** [comment]
ah thank you :D
sorry again ;)
